### ISSUE TITLE
Remove package-metadata.json

### ISSUE THREAD

**Issue by Kout** [gs/sublime-text-go-to-file#6]
After installing the package everything worked just fine ‒ for a while. Untill I discovered, Sublime keeps deleting the cloned folder with the GoToFile package. The solution, which worked for me, I found here: https://forum.sublimetext.com/t/sublime-keeps-deleting-my-loose-packages/15691/3

So either remove `package-metadata.json` from the repository, or update installation notes to remove it manually after install.

**Comment by gs** [comment]
removed in 03d9161ee88d97da49c27bdb537de0aca9b91391.

Thank you and enjoy
